/*
proxima-core-engine

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CallTag type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CallTag{}

// CallTag struct for CallTag
type CallTag struct {
	// The call tag id.
	CallTagId int32 `json:"call_tag_id"`
	Name string `json:"name"`
	Description NullableString `json:"description,omitempty"`
}

type _CallTag CallTag

// NewCallTag instantiates a new CallTag object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCallTag(callTagId int32, name string) *CallTag {
	this := CallTag{}
	this.CallTagId = callTagId
	this.Name = name
	return &this
}

// NewCallTagWithDefaults instantiates a new CallTag object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCallTagWithDefaults() *CallTag {
	this := CallTag{}
	return &this
}

// GetCallTagId returns the CallTagId field value
func (o *CallTag) GetCallTagId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.CallTagId
}

// GetCallTagIdOk returns a tuple with the CallTagId field value
// and a boolean to check if the value has been set.
func (o *CallTag) GetCallTagIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CallTagId, true
}

// SetCallTagId sets field value
func (o *CallTag) SetCallTagId(v int32) {
	o.CallTagId = v
}

// GetName returns the Name field value
func (o *CallTag) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *CallTag) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *CallTag) SetName(v string) {
	o.Name = v
}

// GetDescription returns the Description field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CallTag) GetDescription() string {
	if o == nil || IsNil(o.Description.Get()) {
		var ret string
		return ret
	}
	return *o.Description.Get()
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CallTag) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Description.Get(), o.Description.IsSet()
}

// HasDescription returns a boolean if a field has been set.
func (o *CallTag) HasDescription() bool {
	if o != nil && o.Description.IsSet() {
		return true
	}

	return false
}

// SetDescription gets a reference to the given NullableString and assigns it to the Description field.
func (o *CallTag) SetDescription(v string) {
	o.Description.Set(&v)
}
// SetDescriptionNil sets the value for Description to be an explicit nil
func (o *CallTag) SetDescriptionNil() {
	o.Description.Set(nil)
}

// UnsetDescription ensures that no value is present for Description, not even an explicit nil
func (o *CallTag) UnsetDescription() {
	o.Description.Unset()
}

func (o CallTag) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CallTag) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["call_tag_id"] = o.CallTagId
	toSerialize["name"] = o.Name
	if o.Description.IsSet() {
		toSerialize["description"] = o.Description.Get()
	}
	return toSerialize, nil
}

func (o *CallTag) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"call_tag_id",
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCallTag := _CallTag{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCallTag)

	if err != nil {
		return err
	}

	*o = CallTag(varCallTag)

	return err
}

type NullableCallTag struct {
	value *CallTag
	isSet bool
}

func (v NullableCallTag) Get() *CallTag {
	return v.value
}

func (v *NullableCallTag) Set(val *CallTag) {
	v.value = val
	v.isSet = true
}

func (v NullableCallTag) IsSet() bool {
	return v.isSet
}

func (v *NullableCallTag) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCallTag(val *CallTag) *NullableCallTag {
	return &NullableCallTag{value: val, isSet: true}
}

func (v NullableCallTag) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCallTag) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


