/*
proxima-core-engine

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ClientUser type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ClientUser{}

// ClientUser Handles serialization and deserialization of user objects
type ClientUser struct {
	Id int32 `json:"id"`
	FirstName string `json:"first_name"`
	LastName string `json:"last_name"`
	Username string `json:"username"`
	Phonenumber NullableString `json:"phonenumber,omitempty"`
	Email string `json:"email"`
	Gender NullableAdminGender `json:"gender,omitempty"`
	DOB NullableString `json:"DOB,omitempty"`
	Password string `json:"password"`
	Token string `json:"token"`
	Profile ClientProfile `json:"profile"`
	ProfilePhoto string `json:"profile_photo"`
	Country string `json:"country"`
	County string `json:"county"`
	City string `json:"city"`
	PostalCode string `json:"postal_code"`
	Location string `json:"location"`
}

type _ClientUser ClientUser

// NewClientUser instantiates a new ClientUser object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewClientUser(id int32, firstName string, lastName string, username string, email string, password string, token string, profile ClientProfile, profilePhoto string, country string, county string, city string, postalCode string, location string) *ClientUser {
	this := ClientUser{}
	this.Id = id
	this.FirstName = firstName
	this.LastName = lastName
	this.Username = username
	this.Email = email
	this.Password = password
	this.Token = token
	this.Profile = profile
	this.ProfilePhoto = profilePhoto
	this.Country = country
	this.County = county
	this.City = city
	this.PostalCode = postalCode
	this.Location = location
	return &this
}

// NewClientUserWithDefaults instantiates a new ClientUser object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewClientUserWithDefaults() *ClientUser {
	this := ClientUser{}
	return &this
}

// GetId returns the Id field value
func (o *ClientUser) GetId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *ClientUser) GetIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *ClientUser) SetId(v int32) {
	o.Id = v
}

// GetFirstName returns the FirstName field value
func (o *ClientUser) GetFirstName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.FirstName
}

// GetFirstNameOk returns a tuple with the FirstName field value
// and a boolean to check if the value has been set.
func (o *ClientUser) GetFirstNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FirstName, true
}

// SetFirstName sets field value
func (o *ClientUser) SetFirstName(v string) {
	o.FirstName = v
}

// GetLastName returns the LastName field value
func (o *ClientUser) GetLastName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.LastName
}

// GetLastNameOk returns a tuple with the LastName field value
// and a boolean to check if the value has been set.
func (o *ClientUser) GetLastNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LastName, true
}

// SetLastName sets field value
func (o *ClientUser) SetLastName(v string) {
	o.LastName = v
}

// GetUsername returns the Username field value
func (o *ClientUser) GetUsername() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Username
}

// GetUsernameOk returns a tuple with the Username field value
// and a boolean to check if the value has been set.
func (o *ClientUser) GetUsernameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Username, true
}

// SetUsername sets field value
func (o *ClientUser) SetUsername(v string) {
	o.Username = v
}

// GetPhonenumber returns the Phonenumber field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ClientUser) GetPhonenumber() string {
	if o == nil || IsNil(o.Phonenumber.Get()) {
		var ret string
		return ret
	}
	return *o.Phonenumber.Get()
}

// GetPhonenumberOk returns a tuple with the Phonenumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ClientUser) GetPhonenumberOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Phonenumber.Get(), o.Phonenumber.IsSet()
}

// HasPhonenumber returns a boolean if a field has been set.
func (o *ClientUser) HasPhonenumber() bool {
	if o != nil && o.Phonenumber.IsSet() {
		return true
	}

	return false
}

// SetPhonenumber gets a reference to the given NullableString and assigns it to the Phonenumber field.
func (o *ClientUser) SetPhonenumber(v string) {
	o.Phonenumber.Set(&v)
}
// SetPhonenumberNil sets the value for Phonenumber to be an explicit nil
func (o *ClientUser) SetPhonenumberNil() {
	o.Phonenumber.Set(nil)
}

// UnsetPhonenumber ensures that no value is present for Phonenumber, not even an explicit nil
func (o *ClientUser) UnsetPhonenumber() {
	o.Phonenumber.Unset()
}

// GetEmail returns the Email field value
func (o *ClientUser) GetEmail() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Email
}

// GetEmailOk returns a tuple with the Email field value
// and a boolean to check if the value has been set.
func (o *ClientUser) GetEmailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Email, true
}

// SetEmail sets field value
func (o *ClientUser) SetEmail(v string) {
	o.Email = v
}

// GetGender returns the Gender field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ClientUser) GetGender() AdminGender {
	if o == nil || IsNil(o.Gender.Get()) {
		var ret AdminGender
		return ret
	}
	return *o.Gender.Get()
}

// GetGenderOk returns a tuple with the Gender field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ClientUser) GetGenderOk() (*AdminGender, bool) {
	if o == nil {
		return nil, false
	}
	return o.Gender.Get(), o.Gender.IsSet()
}

// HasGender returns a boolean if a field has been set.
func (o *ClientUser) HasGender() bool {
	if o != nil && o.Gender.IsSet() {
		return true
	}

	return false
}

// SetGender gets a reference to the given NullableAdminGender and assigns it to the Gender field.
func (o *ClientUser) SetGender(v AdminGender) {
	o.Gender.Set(&v)
}
// SetGenderNil sets the value for Gender to be an explicit nil
func (o *ClientUser) SetGenderNil() {
	o.Gender.Set(nil)
}

// UnsetGender ensures that no value is present for Gender, not even an explicit nil
func (o *ClientUser) UnsetGender() {
	o.Gender.Unset()
}

// GetDOB returns the DOB field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ClientUser) GetDOB() string {
	if o == nil || IsNil(o.DOB.Get()) {
		var ret string
		return ret
	}
	return *o.DOB.Get()
}

// GetDOBOk returns a tuple with the DOB field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ClientUser) GetDOBOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.DOB.Get(), o.DOB.IsSet()
}

// HasDOB returns a boolean if a field has been set.
func (o *ClientUser) HasDOB() bool {
	if o != nil && o.DOB.IsSet() {
		return true
	}

	return false
}

// SetDOB gets a reference to the given NullableString and assigns it to the DOB field.
func (o *ClientUser) SetDOB(v string) {
	o.DOB.Set(&v)
}
// SetDOBNil sets the value for DOB to be an explicit nil
func (o *ClientUser) SetDOBNil() {
	o.DOB.Set(nil)
}

// UnsetDOB ensures that no value is present for DOB, not even an explicit nil
func (o *ClientUser) UnsetDOB() {
	o.DOB.Unset()
}

// GetPassword returns the Password field value
func (o *ClientUser) GetPassword() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Password
}

// GetPasswordOk returns a tuple with the Password field value
// and a boolean to check if the value has been set.
func (o *ClientUser) GetPasswordOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Password, true
}

// SetPassword sets field value
func (o *ClientUser) SetPassword(v string) {
	o.Password = v
}

// GetToken returns the Token field value
func (o *ClientUser) GetToken() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Token
}

// GetTokenOk returns a tuple with the Token field value
// and a boolean to check if the value has been set.
func (o *ClientUser) GetTokenOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Token, true
}

// SetToken sets field value
func (o *ClientUser) SetToken(v string) {
	o.Token = v
}

// GetProfile returns the Profile field value
func (o *ClientUser) GetProfile() ClientProfile {
	if o == nil {
		var ret ClientProfile
		return ret
	}

	return o.Profile
}

// GetProfileOk returns a tuple with the Profile field value
// and a boolean to check if the value has been set.
func (o *ClientUser) GetProfileOk() (*ClientProfile, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Profile, true
}

// SetProfile sets field value
func (o *ClientUser) SetProfile(v ClientProfile) {
	o.Profile = v
}

// GetProfilePhoto returns the ProfilePhoto field value
func (o *ClientUser) GetProfilePhoto() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ProfilePhoto
}

// GetProfilePhotoOk returns a tuple with the ProfilePhoto field value
// and a boolean to check if the value has been set.
func (o *ClientUser) GetProfilePhotoOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ProfilePhoto, true
}

// SetProfilePhoto sets field value
func (o *ClientUser) SetProfilePhoto(v string) {
	o.ProfilePhoto = v
}

// GetCountry returns the Country field value
func (o *ClientUser) GetCountry() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Country
}

// GetCountryOk returns a tuple with the Country field value
// and a boolean to check if the value has been set.
func (o *ClientUser) GetCountryOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Country, true
}

// SetCountry sets field value
func (o *ClientUser) SetCountry(v string) {
	o.Country = v
}

// GetCounty returns the County field value
func (o *ClientUser) GetCounty() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.County
}

// GetCountyOk returns a tuple with the County field value
// and a boolean to check if the value has been set.
func (o *ClientUser) GetCountyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.County, true
}

// SetCounty sets field value
func (o *ClientUser) SetCounty(v string) {
	o.County = v
}

// GetCity returns the City field value
func (o *ClientUser) GetCity() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.City
}

// GetCityOk returns a tuple with the City field value
// and a boolean to check if the value has been set.
func (o *ClientUser) GetCityOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.City, true
}

// SetCity sets field value
func (o *ClientUser) SetCity(v string) {
	o.City = v
}

// GetPostalCode returns the PostalCode field value
func (o *ClientUser) GetPostalCode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PostalCode
}

// GetPostalCodeOk returns a tuple with the PostalCode field value
// and a boolean to check if the value has been set.
func (o *ClientUser) GetPostalCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PostalCode, true
}

// SetPostalCode sets field value
func (o *ClientUser) SetPostalCode(v string) {
	o.PostalCode = v
}

// GetLocation returns the Location field value
func (o *ClientUser) GetLocation() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Location
}

// GetLocationOk returns a tuple with the Location field value
// and a boolean to check if the value has been set.
func (o *ClientUser) GetLocationOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Location, true
}

// SetLocation sets field value
func (o *ClientUser) SetLocation(v string) {
	o.Location = v
}

func (o ClientUser) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ClientUser) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["first_name"] = o.FirstName
	toSerialize["last_name"] = o.LastName
	toSerialize["username"] = o.Username
	if o.Phonenumber.IsSet() {
		toSerialize["phonenumber"] = o.Phonenumber.Get()
	}
	toSerialize["email"] = o.Email
	if o.Gender.IsSet() {
		toSerialize["gender"] = o.Gender.Get()
	}
	if o.DOB.IsSet() {
		toSerialize["DOB"] = o.DOB.Get()
	}
	toSerialize["password"] = o.Password
	toSerialize["token"] = o.Token
	toSerialize["profile"] = o.Profile
	toSerialize["profile_photo"] = o.ProfilePhoto
	toSerialize["country"] = o.Country
	toSerialize["county"] = o.County
	toSerialize["city"] = o.City
	toSerialize["postal_code"] = o.PostalCode
	toSerialize["location"] = o.Location
	return toSerialize, nil
}

func (o *ClientUser) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"first_name",
		"last_name",
		"username",
		"email",
		"password",
		"token",
		"profile",
		"profile_photo",
		"country",
		"county",
		"city",
		"postal_code",
		"location",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varClientUser := _ClientUser{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varClientUser)

	if err != nil {
		return err
	}

	*o = ClientUser(varClientUser)

	return err
}

type NullableClientUser struct {
	value *ClientUser
	isSet bool
}

func (v NullableClientUser) Get() *ClientUser {
	return v.value
}

func (v *NullableClientUser) Set(val *ClientUser) {
	v.value = val
	v.isSet = true
}

func (v NullableClientUser) IsSet() bool {
	return v.isSet
}

func (v *NullableClientUser) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableClientUser(val *ClientUser) *NullableClientUser {
	return &NullableClientUser{value: val, isSet: true}
}

func (v NullableClientUser) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableClientUser) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


