/*
proxima-core-engine

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the PatchedAgentPerformance type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PatchedAgentPerformance{}

// PatchedAgentPerformance struct for PatchedAgentPerformance
type PatchedAgentPerformance struct {
	AgentPerformanceId *int32 `json:"agent_performance_id,omitempty"`
	TenantId *TenantInfo `json:"tenant_id,omitempty"`
	// Average duration of calls handled by the agent.
	AverageCallDuration *string `json:"average_call_duration,omitempty"`
	// Average satisfaction score from customer feedback.
	AverageSatisfactionScore *float64 `json:"average_satisfaction_score,omitempty"`
	// Percentage of calls resolved by the agent.
	ResolutionRate *float64 `json:"resolution_rate,omitempty"`
	// Total number of calls handled by the agent.
	TotalCallsHandled *int32 `json:"total_calls_handled,omitempty"`
}

// NewPatchedAgentPerformance instantiates a new PatchedAgentPerformance object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPatchedAgentPerformance() *PatchedAgentPerformance {
	this := PatchedAgentPerformance{}
	return &this
}

// NewPatchedAgentPerformanceWithDefaults instantiates a new PatchedAgentPerformance object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPatchedAgentPerformanceWithDefaults() *PatchedAgentPerformance {
	this := PatchedAgentPerformance{}
	return &this
}

// GetAgentPerformanceId returns the AgentPerformanceId field value if set, zero value otherwise.
func (o *PatchedAgentPerformance) GetAgentPerformanceId() int32 {
	if o == nil || IsNil(o.AgentPerformanceId) {
		var ret int32
		return ret
	}
	return *o.AgentPerformanceId
}

// GetAgentPerformanceIdOk returns a tuple with the AgentPerformanceId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchedAgentPerformance) GetAgentPerformanceIdOk() (*int32, bool) {
	if o == nil || IsNil(o.AgentPerformanceId) {
		return nil, false
	}
	return o.AgentPerformanceId, true
}

// HasAgentPerformanceId returns a boolean if a field has been set.
func (o *PatchedAgentPerformance) HasAgentPerformanceId() bool {
	if o != nil && !IsNil(o.AgentPerformanceId) {
		return true
	}

	return false
}

// SetAgentPerformanceId gets a reference to the given int32 and assigns it to the AgentPerformanceId field.
func (o *PatchedAgentPerformance) SetAgentPerformanceId(v int32) {
	o.AgentPerformanceId = &v
}

// GetTenantId returns the TenantId field value if set, zero value otherwise.
func (o *PatchedAgentPerformance) GetTenantId() TenantInfo {
	if o == nil || IsNil(o.TenantId) {
		var ret TenantInfo
		return ret
	}
	return *o.TenantId
}

// GetTenantIdOk returns a tuple with the TenantId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchedAgentPerformance) GetTenantIdOk() (*TenantInfo, bool) {
	if o == nil || IsNil(o.TenantId) {
		return nil, false
	}
	return o.TenantId, true
}

// HasTenantId returns a boolean if a field has been set.
func (o *PatchedAgentPerformance) HasTenantId() bool {
	if o != nil && !IsNil(o.TenantId) {
		return true
	}

	return false
}

// SetTenantId gets a reference to the given TenantInfo and assigns it to the TenantId field.
func (o *PatchedAgentPerformance) SetTenantId(v TenantInfo) {
	o.TenantId = &v
}

// GetAverageCallDuration returns the AverageCallDuration field value if set, zero value otherwise.
func (o *PatchedAgentPerformance) GetAverageCallDuration() string {
	if o == nil || IsNil(o.AverageCallDuration) {
		var ret string
		return ret
	}
	return *o.AverageCallDuration
}

// GetAverageCallDurationOk returns a tuple with the AverageCallDuration field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchedAgentPerformance) GetAverageCallDurationOk() (*string, bool) {
	if o == nil || IsNil(o.AverageCallDuration) {
		return nil, false
	}
	return o.AverageCallDuration, true
}

// HasAverageCallDuration returns a boolean if a field has been set.
func (o *PatchedAgentPerformance) HasAverageCallDuration() bool {
	if o != nil && !IsNil(o.AverageCallDuration) {
		return true
	}

	return false
}

// SetAverageCallDuration gets a reference to the given string and assigns it to the AverageCallDuration field.
func (o *PatchedAgentPerformance) SetAverageCallDuration(v string) {
	o.AverageCallDuration = &v
}

// GetAverageSatisfactionScore returns the AverageSatisfactionScore field value if set, zero value otherwise.
func (o *PatchedAgentPerformance) GetAverageSatisfactionScore() float64 {
	if o == nil || IsNil(o.AverageSatisfactionScore) {
		var ret float64
		return ret
	}
	return *o.AverageSatisfactionScore
}

// GetAverageSatisfactionScoreOk returns a tuple with the AverageSatisfactionScore field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchedAgentPerformance) GetAverageSatisfactionScoreOk() (*float64, bool) {
	if o == nil || IsNil(o.AverageSatisfactionScore) {
		return nil, false
	}
	return o.AverageSatisfactionScore, true
}

// HasAverageSatisfactionScore returns a boolean if a field has been set.
func (o *PatchedAgentPerformance) HasAverageSatisfactionScore() bool {
	if o != nil && !IsNil(o.AverageSatisfactionScore) {
		return true
	}

	return false
}

// SetAverageSatisfactionScore gets a reference to the given float64 and assigns it to the AverageSatisfactionScore field.
func (o *PatchedAgentPerformance) SetAverageSatisfactionScore(v float64) {
	o.AverageSatisfactionScore = &v
}

// GetResolutionRate returns the ResolutionRate field value if set, zero value otherwise.
func (o *PatchedAgentPerformance) GetResolutionRate() float64 {
	if o == nil || IsNil(o.ResolutionRate) {
		var ret float64
		return ret
	}
	return *o.ResolutionRate
}

// GetResolutionRateOk returns a tuple with the ResolutionRate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchedAgentPerformance) GetResolutionRateOk() (*float64, bool) {
	if o == nil || IsNil(o.ResolutionRate) {
		return nil, false
	}
	return o.ResolutionRate, true
}

// HasResolutionRate returns a boolean if a field has been set.
func (o *PatchedAgentPerformance) HasResolutionRate() bool {
	if o != nil && !IsNil(o.ResolutionRate) {
		return true
	}

	return false
}

// SetResolutionRate gets a reference to the given float64 and assigns it to the ResolutionRate field.
func (o *PatchedAgentPerformance) SetResolutionRate(v float64) {
	o.ResolutionRate = &v
}

// GetTotalCallsHandled returns the TotalCallsHandled field value if set, zero value otherwise.
func (o *PatchedAgentPerformance) GetTotalCallsHandled() int32 {
	if o == nil || IsNil(o.TotalCallsHandled) {
		var ret int32
		return ret
	}
	return *o.TotalCallsHandled
}

// GetTotalCallsHandledOk returns a tuple with the TotalCallsHandled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchedAgentPerformance) GetTotalCallsHandledOk() (*int32, bool) {
	if o == nil || IsNil(o.TotalCallsHandled) {
		return nil, false
	}
	return o.TotalCallsHandled, true
}

// HasTotalCallsHandled returns a boolean if a field has been set.
func (o *PatchedAgentPerformance) HasTotalCallsHandled() bool {
	if o != nil && !IsNil(o.TotalCallsHandled) {
		return true
	}

	return false
}

// SetTotalCallsHandled gets a reference to the given int32 and assigns it to the TotalCallsHandled field.
func (o *PatchedAgentPerformance) SetTotalCallsHandled(v int32) {
	o.TotalCallsHandled = &v
}

func (o PatchedAgentPerformance) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PatchedAgentPerformance) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AgentPerformanceId) {
		toSerialize["agent_performance_id"] = o.AgentPerformanceId
	}
	if !IsNil(o.TenantId) {
		toSerialize["tenant_id"] = o.TenantId
	}
	if !IsNil(o.AverageCallDuration) {
		toSerialize["average_call_duration"] = o.AverageCallDuration
	}
	if !IsNil(o.AverageSatisfactionScore) {
		toSerialize["average_satisfaction_score"] = o.AverageSatisfactionScore
	}
	if !IsNil(o.ResolutionRate) {
		toSerialize["resolution_rate"] = o.ResolutionRate
	}
	if !IsNil(o.TotalCallsHandled) {
		toSerialize["total_calls_handled"] = o.TotalCallsHandled
	}
	return toSerialize, nil
}

type NullablePatchedAgentPerformance struct {
	value *PatchedAgentPerformance
	isSet bool
}

func (v NullablePatchedAgentPerformance) Get() *PatchedAgentPerformance {
	return v.value
}

func (v *NullablePatchedAgentPerformance) Set(val *PatchedAgentPerformance) {
	v.value = val
	v.isSet = true
}

func (v NullablePatchedAgentPerformance) IsSet() bool {
	return v.isSet
}

func (v *NullablePatchedAgentPerformance) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePatchedAgentPerformance(val *PatchedAgentPerformance) *NullablePatchedAgentPerformance {
	return &NullablePatchedAgentPerformance{value: val, isSet: true}
}

func (v NullablePatchedAgentPerformance) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePatchedAgentPerformance) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


