/*
proxima-core-engine

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"time"
)

// checks if the PatchedCallResolution type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PatchedCallResolution{}

// PatchedCallResolution struct for PatchedCallResolution
type PatchedCallResolution struct {
	// The call resolution id.
	CallResolutionId *int32 `json:"call_resolution_id,omitempty"`
	Call *Call `json:"call,omitempty"`
	Status *CallResolutionStatusEnum `json:"status,omitempty"`
	PendingActions interface{} `json:"pending_actions,omitempty"`
	FollowUpRequired *bool `json:"follow_up_required,omitempty"`
	FollowUpDate NullableTime `json:"follow_up_date,omitempty"`
}

// NewPatchedCallResolution instantiates a new PatchedCallResolution object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPatchedCallResolution() *PatchedCallResolution {
	this := PatchedCallResolution{}
	return &this
}

// NewPatchedCallResolutionWithDefaults instantiates a new PatchedCallResolution object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPatchedCallResolutionWithDefaults() *PatchedCallResolution {
	this := PatchedCallResolution{}
	return &this
}

// GetCallResolutionId returns the CallResolutionId field value if set, zero value otherwise.
func (o *PatchedCallResolution) GetCallResolutionId() int32 {
	if o == nil || IsNil(o.CallResolutionId) {
		var ret int32
		return ret
	}
	return *o.CallResolutionId
}

// GetCallResolutionIdOk returns a tuple with the CallResolutionId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchedCallResolution) GetCallResolutionIdOk() (*int32, bool) {
	if o == nil || IsNil(o.CallResolutionId) {
		return nil, false
	}
	return o.CallResolutionId, true
}

// HasCallResolutionId returns a boolean if a field has been set.
func (o *PatchedCallResolution) HasCallResolutionId() bool {
	if o != nil && !IsNil(o.CallResolutionId) {
		return true
	}

	return false
}

// SetCallResolutionId gets a reference to the given int32 and assigns it to the CallResolutionId field.
func (o *PatchedCallResolution) SetCallResolutionId(v int32) {
	o.CallResolutionId = &v
}

// GetCall returns the Call field value if set, zero value otherwise.
func (o *PatchedCallResolution) GetCall() Call {
	if o == nil || IsNil(o.Call) {
		var ret Call
		return ret
	}
	return *o.Call
}

// GetCallOk returns a tuple with the Call field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchedCallResolution) GetCallOk() (*Call, bool) {
	if o == nil || IsNil(o.Call) {
		return nil, false
	}
	return o.Call, true
}

// HasCall returns a boolean if a field has been set.
func (o *PatchedCallResolution) HasCall() bool {
	if o != nil && !IsNil(o.Call) {
		return true
	}

	return false
}

// SetCall gets a reference to the given Call and assigns it to the Call field.
func (o *PatchedCallResolution) SetCall(v Call) {
	o.Call = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *PatchedCallResolution) GetStatus() CallResolutionStatusEnum {
	if o == nil || IsNil(o.Status) {
		var ret CallResolutionStatusEnum
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchedCallResolution) GetStatusOk() (*CallResolutionStatusEnum, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *PatchedCallResolution) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given CallResolutionStatusEnum and assigns it to the Status field.
func (o *PatchedCallResolution) SetStatus(v CallResolutionStatusEnum) {
	o.Status = &v
}

// GetPendingActions returns the PendingActions field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PatchedCallResolution) GetPendingActions() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.PendingActions
}

// GetPendingActionsOk returns a tuple with the PendingActions field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PatchedCallResolution) GetPendingActionsOk() (*interface{}, bool) {
	if o == nil || IsNil(o.PendingActions) {
		return nil, false
	}
	return &o.PendingActions, true
}

// HasPendingActions returns a boolean if a field has been set.
func (o *PatchedCallResolution) HasPendingActions() bool {
	if o != nil && !IsNil(o.PendingActions) {
		return true
	}

	return false
}

// SetPendingActions gets a reference to the given interface{} and assigns it to the PendingActions field.
func (o *PatchedCallResolution) SetPendingActions(v interface{}) {
	o.PendingActions = v
}

// GetFollowUpRequired returns the FollowUpRequired field value if set, zero value otherwise.
func (o *PatchedCallResolution) GetFollowUpRequired() bool {
	if o == nil || IsNil(o.FollowUpRequired) {
		var ret bool
		return ret
	}
	return *o.FollowUpRequired
}

// GetFollowUpRequiredOk returns a tuple with the FollowUpRequired field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchedCallResolution) GetFollowUpRequiredOk() (*bool, bool) {
	if o == nil || IsNil(o.FollowUpRequired) {
		return nil, false
	}
	return o.FollowUpRequired, true
}

// HasFollowUpRequired returns a boolean if a field has been set.
func (o *PatchedCallResolution) HasFollowUpRequired() bool {
	if o != nil && !IsNil(o.FollowUpRequired) {
		return true
	}

	return false
}

// SetFollowUpRequired gets a reference to the given bool and assigns it to the FollowUpRequired field.
func (o *PatchedCallResolution) SetFollowUpRequired(v bool) {
	o.FollowUpRequired = &v
}

// GetFollowUpDate returns the FollowUpDate field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PatchedCallResolution) GetFollowUpDate() time.Time {
	if o == nil || IsNil(o.FollowUpDate.Get()) {
		var ret time.Time
		return ret
	}
	return *o.FollowUpDate.Get()
}

// GetFollowUpDateOk returns a tuple with the FollowUpDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PatchedCallResolution) GetFollowUpDateOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.FollowUpDate.Get(), o.FollowUpDate.IsSet()
}

// HasFollowUpDate returns a boolean if a field has been set.
func (o *PatchedCallResolution) HasFollowUpDate() bool {
	if o != nil && o.FollowUpDate.IsSet() {
		return true
	}

	return false
}

// SetFollowUpDate gets a reference to the given NullableTime and assigns it to the FollowUpDate field.
func (o *PatchedCallResolution) SetFollowUpDate(v time.Time) {
	o.FollowUpDate.Set(&v)
}
// SetFollowUpDateNil sets the value for FollowUpDate to be an explicit nil
func (o *PatchedCallResolution) SetFollowUpDateNil() {
	o.FollowUpDate.Set(nil)
}

// UnsetFollowUpDate ensures that no value is present for FollowUpDate, not even an explicit nil
func (o *PatchedCallResolution) UnsetFollowUpDate() {
	o.FollowUpDate.Unset()
}

func (o PatchedCallResolution) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PatchedCallResolution) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.CallResolutionId) {
		toSerialize["call_resolution_id"] = o.CallResolutionId
	}
	if !IsNil(o.Call) {
		toSerialize["call"] = o.Call
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if o.PendingActions != nil {
		toSerialize["pending_actions"] = o.PendingActions
	}
	if !IsNil(o.FollowUpRequired) {
		toSerialize["follow_up_required"] = o.FollowUpRequired
	}
	if o.FollowUpDate.IsSet() {
		toSerialize["follow_up_date"] = o.FollowUpDate.Get()
	}
	return toSerialize, nil
}

type NullablePatchedCallResolution struct {
	value *PatchedCallResolution
	isSet bool
}

func (v NullablePatchedCallResolution) Get() *PatchedCallResolution {
	return v.value
}

func (v *NullablePatchedCallResolution) Set(val *PatchedCallResolution) {
	v.value = val
	v.isSet = true
}

func (v NullablePatchedCallResolution) IsSet() bool {
	return v.isSet
}

func (v *NullablePatchedCallResolution) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePatchedCallResolution(val *PatchedCallResolution) *NullablePatchedCallResolution {
	return &NullablePatchedCallResolution{value: val, isSet: true}
}

func (v NullablePatchedCallResolution) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePatchedCallResolution) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


