/*
proxima-core-engine

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the UnverifiedUsers type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UnverifiedUsers{}

// UnverifiedUsers struct for UnverifiedUsers
type UnverifiedUsers struct {
	Email string `json:"email"`
	CreatedAt *time.Time `json:"created_at,omitempty"`
	UserType NullableUserType3daEnum `json:"user_type,omitempty"`
}

type _UnverifiedUsers UnverifiedUsers

// NewUnverifiedUsers instantiates a new UnverifiedUsers object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUnverifiedUsers(email string) *UnverifiedUsers {
	this := UnverifiedUsers{}
	this.Email = email
	return &this
}

// NewUnverifiedUsersWithDefaults instantiates a new UnverifiedUsers object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUnverifiedUsersWithDefaults() *UnverifiedUsers {
	this := UnverifiedUsers{}
	return &this
}

// GetEmail returns the Email field value
func (o *UnverifiedUsers) GetEmail() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Email
}

// GetEmailOk returns a tuple with the Email field value
// and a boolean to check if the value has been set.
func (o *UnverifiedUsers) GetEmailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Email, true
}

// SetEmail sets field value
func (o *UnverifiedUsers) SetEmail(v string) {
	o.Email = v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *UnverifiedUsers) GetCreatedAt() time.Time {
	if o == nil || IsNil(o.CreatedAt) {
		var ret time.Time
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UnverifiedUsers) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *UnverifiedUsers) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given time.Time and assigns it to the CreatedAt field.
func (o *UnverifiedUsers) SetCreatedAt(v time.Time) {
	o.CreatedAt = &v
}

// GetUserType returns the UserType field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UnverifiedUsers) GetUserType() UserType3daEnum {
	if o == nil || IsNil(o.UserType.Get()) {
		var ret UserType3daEnum
		return ret
	}
	return *o.UserType.Get()
}

// GetUserTypeOk returns a tuple with the UserType field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UnverifiedUsers) GetUserTypeOk() (*UserType3daEnum, bool) {
	if o == nil {
		return nil, false
	}
	return o.UserType.Get(), o.UserType.IsSet()
}

// HasUserType returns a boolean if a field has been set.
func (o *UnverifiedUsers) HasUserType() bool {
	if o != nil && o.UserType.IsSet() {
		return true
	}

	return false
}

// SetUserType gets a reference to the given NullableUserType3daEnum and assigns it to the UserType field.
func (o *UnverifiedUsers) SetUserType(v UserType3daEnum) {
	o.UserType.Set(&v)
}
// SetUserTypeNil sets the value for UserType to be an explicit nil
func (o *UnverifiedUsers) SetUserTypeNil() {
	o.UserType.Set(nil)
}

// UnsetUserType ensures that no value is present for UserType, not even an explicit nil
func (o *UnverifiedUsers) UnsetUserType() {
	o.UserType.Unset()
}

func (o UnverifiedUsers) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UnverifiedUsers) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["email"] = o.Email
	if !IsNil(o.CreatedAt) {
		toSerialize["created_at"] = o.CreatedAt
	}
	if o.UserType.IsSet() {
		toSerialize["user_type"] = o.UserType.Get()
	}
	return toSerialize, nil
}

func (o *UnverifiedUsers) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"email",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUnverifiedUsers := _UnverifiedUsers{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUnverifiedUsers)

	if err != nil {
		return err
	}

	*o = UnverifiedUsers(varUnverifiedUsers)

	return err
}

type NullableUnverifiedUsers struct {
	value *UnverifiedUsers
	isSet bool
}

func (v NullableUnverifiedUsers) Get() *UnverifiedUsers {
	return v.value
}

func (v *NullableUnverifiedUsers) Set(val *UnverifiedUsers) {
	v.value = val
	v.isSet = true
}

func (v NullableUnverifiedUsers) IsSet() bool {
	return v.isSet
}

func (v *NullableUnverifiedUsers) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUnverifiedUsers(val *UnverifiedUsers) *NullableUnverifiedUsers {
	return &NullableUnverifiedUsers{value: val, isSet: true}
}

func (v NullableUnverifiedUsers) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUnverifiedUsers) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


