/*
proxima-core-engine

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ResetPasswordEmailRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ResetPasswordEmailRequest{}

// ResetPasswordEmailRequest struct for ResetPasswordEmailRequest
type ResetPasswordEmailRequest struct {
	Email string `json:"email"`
	RedirectUrl *string `json:"redirect_url,omitempty"`
}

type _ResetPasswordEmailRequest ResetPasswordEmailRequest

// NewResetPasswordEmailRequest instantiates a new ResetPasswordEmailRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewResetPasswordEmailRequest(email string) *ResetPasswordEmailRequest {
	this := ResetPasswordEmailRequest{}
	this.Email = email
	return &this
}

// NewResetPasswordEmailRequestWithDefaults instantiates a new ResetPasswordEmailRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewResetPasswordEmailRequestWithDefaults() *ResetPasswordEmailRequest {
	this := ResetPasswordEmailRequest{}
	return &this
}

// GetEmail returns the Email field value
func (o *ResetPasswordEmailRequest) GetEmail() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Email
}

// GetEmailOk returns a tuple with the Email field value
// and a boolean to check if the value has been set.
func (o *ResetPasswordEmailRequest) GetEmailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Email, true
}

// SetEmail sets field value
func (o *ResetPasswordEmailRequest) SetEmail(v string) {
	o.Email = v
}

// GetRedirectUrl returns the RedirectUrl field value if set, zero value otherwise.
func (o *ResetPasswordEmailRequest) GetRedirectUrl() string {
	if o == nil || IsNil(o.RedirectUrl) {
		var ret string
		return ret
	}
	return *o.RedirectUrl
}

// GetRedirectUrlOk returns a tuple with the RedirectUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResetPasswordEmailRequest) GetRedirectUrlOk() (*string, bool) {
	if o == nil || IsNil(o.RedirectUrl) {
		return nil, false
	}
	return o.RedirectUrl, true
}

// HasRedirectUrl returns a boolean if a field has been set.
func (o *ResetPasswordEmailRequest) HasRedirectUrl() bool {
	if o != nil && !IsNil(o.RedirectUrl) {
		return true
	}

	return false
}

// SetRedirectUrl gets a reference to the given string and assigns it to the RedirectUrl field.
func (o *ResetPasswordEmailRequest) SetRedirectUrl(v string) {
	o.RedirectUrl = &v
}

func (o ResetPasswordEmailRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ResetPasswordEmailRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["email"] = o.Email
	if !IsNil(o.RedirectUrl) {
		toSerialize["redirect_url"] = o.RedirectUrl
	}
	return toSerialize, nil
}

func (o *ResetPasswordEmailRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"email",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varResetPasswordEmailRequest := _ResetPasswordEmailRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varResetPasswordEmailRequest)

	if err != nil {
		return err
	}

	*o = ResetPasswordEmailRequest(varResetPasswordEmailRequest)

	return err
}

type NullableResetPasswordEmailRequest struct {
	value *ResetPasswordEmailRequest
	isSet bool
}

func (v NullableResetPasswordEmailRequest) Get() *ResetPasswordEmailRequest {
	return v.value
}

func (v *NullableResetPasswordEmailRequest) Set(val *ResetPasswordEmailRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableResetPasswordEmailRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableResetPasswordEmailRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableResetPasswordEmailRequest(val *ResetPasswordEmailRequest) *NullableResetPasswordEmailRequest {
	return &NullableResetPasswordEmailRequest{value: val, isSet: true}
}

func (v NullableResetPasswordEmailRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableResetPasswordEmailRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


