/*
proxima-core-engine

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the FreeTrialEnroll type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FreeTrialEnroll{}

// FreeTrialEnroll struct for FreeTrialEnroll
type FreeTrialEnroll struct {
	Email string `json:"email"`
	TenantId int32 `json:"tenant_id"`
}

type _FreeTrialEnroll FreeTrialEnroll

// NewFreeTrialEnroll instantiates a new FreeTrialEnroll object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFreeTrialEnroll(email string, tenantId int32) *FreeTrialEnroll {
	this := FreeTrialEnroll{}
	this.Email = email
	this.TenantId = tenantId
	return &this
}

// NewFreeTrialEnrollWithDefaults instantiates a new FreeTrialEnroll object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFreeTrialEnrollWithDefaults() *FreeTrialEnroll {
	this := FreeTrialEnroll{}
	return &this
}

// GetEmail returns the Email field value
func (o *FreeTrialEnroll) GetEmail() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Email
}

// GetEmailOk returns a tuple with the Email field value
// and a boolean to check if the value has been set.
func (o *FreeTrialEnroll) GetEmailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Email, true
}

// SetEmail sets field value
func (o *FreeTrialEnroll) SetEmail(v string) {
	o.Email = v
}

// GetTenantId returns the TenantId field value
func (o *FreeTrialEnroll) GetTenantId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.TenantId
}

// GetTenantIdOk returns a tuple with the TenantId field value
// and a boolean to check if the value has been set.
func (o *FreeTrialEnroll) GetTenantIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TenantId, true
}

// SetTenantId sets field value
func (o *FreeTrialEnroll) SetTenantId(v int32) {
	o.TenantId = v
}

func (o FreeTrialEnroll) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FreeTrialEnroll) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["email"] = o.Email
	toSerialize["tenant_id"] = o.TenantId
	return toSerialize, nil
}

func (o *FreeTrialEnroll) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"email",
		"tenant_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varFreeTrialEnroll := _FreeTrialEnroll{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varFreeTrialEnroll)

	if err != nil {
		return err
	}

	*o = FreeTrialEnroll(varFreeTrialEnroll)

	return err
}

type NullableFreeTrialEnroll struct {
	value *FreeTrialEnroll
	isSet bool
}

func (v NullableFreeTrialEnroll) Get() *FreeTrialEnroll {
	return v.value
}

func (v *NullableFreeTrialEnroll) Set(val *FreeTrialEnroll) {
	v.value = val
	v.isSet = true
}

func (v NullableFreeTrialEnroll) IsSet() bool {
	return v.isSet
}

func (v *NullableFreeTrialEnroll) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFreeTrialEnroll(val *FreeTrialEnroll) *NullableFreeTrialEnroll {
	return &NullableFreeTrialEnroll{value: val, isSet: true}
}

func (v NullableFreeTrialEnroll) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFreeTrialEnroll) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


